apps:
  - name: app
    script: ./index.js
    exec_mode: cluster
    instaces: max
    watch: ./
    max_memory_restart: 100M
    env_prod:
      ENVIRONMENT: PRODUCTION
    env_homolog:
      ENVIRONMENT: HOMOLOG